version: '3.3'
services:
  dnsmasq:
    image: 'akinbicer/dnsmasq'
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: dnsmasq
    restart: always
    ports:
      - '50053:50053'